meta_product_name: "Wanderbird"
meta_title: "Help pilots finding the best flying destinations"
meta_description: "Give a goal to your flight, but only by good weather"
meta_image: "full-logo-beta-light.png" # should exist in `app/assets/images/`
