development:
  airport_types_to_import:
    - small_airport
    - medium_airport
    - large_airport
  airport_countries_to_import:
    - FR
    - LU
  airports_white_list:
    - LFJY
  default_weather_calls_validity_hours: 8
  default_weather_tile_precision: 1
  default_weather_tile_depth: 4

test:
  airport_types_to_import:
    - small_airport
    - medium_airport
    - large_airport
  airport_countries_to_import:
    - FR
    - LU
  airports_white_list:
    - LFJY
  default_weather_calls_validity_hours: 8
  default_weather_tile_precision: 1
  default_weather_tile_depth: 4

production:
  airport_types_to_import:
    - small_airport
    - medium_airport
    - large_airport
  airport_countries_to_import:
    - FR
    - LU
  airports_white_list:
    - LFJY
  default_weather_calls_validity_hours: 8
  default_weather_tile_precision: 1
  default_weather_tile_depth: 4


